name = "FLoopsBase"
uuid = "b9860ae5-e623-471e-878b-f6a53c775ea6"
authors = ["Takafumi Arakaki <aka.tkf@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ContextVariablesX = "6add18c4-b38d-439d-96f6-d6bc489c04c5"

[compat]
ContextVariablesX = "0.1"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
